/**
 * Static fixtures backing the mock API. Delete this file once the real
 * backend is live — nothing outside `lib/api.ts` imports it.
 */
import type {
  Category,
  DashboardSummary,
  InventoryItem,
  Location,
  PurchaseOrder,
  ReorderAlert,
  ReportsSummary,
  StockMovement,
  Supplier,
  TeamMember,
  WarehouseMap,
} from "./types";

export const locations: Location[] = [
  { id: "loc-a", name: "Warehouse A", skuCount: 812, utilisation: 0.78 },
  { id: "loc-b", name: "Warehouse B", skuCount: 301, utilisation: 0.52 },
  { id: "loc-s12", name: "Store 12", skuCount: 171, utilisation: 0.34 },
];

export const categories: Category[] = [
  { id: "cat-bev", name: "Beverages" },
  { id: "cat-dry", name: "Dry Goods" },
  { id: "cat-cln", name: "Cleaning" },
  { id: "cat-pkg", name: "Packaging" },
  { id: "cat-snk", name: "Snacks" },
];

export const suppliers: Supplier[] = [
  { id: "sup-north", name: "Northstar Distributors" },
  { id: "sup-meridian", name: "Meridian Foods Co." },
  { id: "sup-brightpack", name: "BrightPack Supplies" },
];

export const items: InventoryItem[] = [
  {
    id: "itm-10234",
    sku: "SKU-10234",
    name: "Organic Rolled Oats 25kg",
    categoryId: "cat-dry",
    categoryName: "Dry Goods",
    locationId: "loc-a",
    locationName: "Warehouse A",
    bin: "Aisle 3, Bin 12",
    onHand: 64,
    reorderPoint: 75,
    reorderQty: 150,
    status: "low",
    supplierId: "sup-north",
    supplierName: "Northstar Distributors",
    unitCost: 18.4,
    sellPrice: 27.99,
    barcode: "8 41234 10234 5",
    imageUrl: null,
  },
  {
    id: "itm-10391",
    sku: "SKU-10391",
    name: "Sparkling Water 12pk",
    categoryId: "cat-bev",
    categoryName: "Beverages",
    locationId: "loc-a",
    locationName: "Warehouse A",
    bin: "Aisle 1, Bin 04",
    onHand: 512,
    reorderPoint: 200,
    reorderQty: 240,
    status: "in_stock",
    supplierId: "sup-meridian",
    supplierName: "Meridian Foods Co.",
    unitCost: 6.2,
    sellPrice: 11.5,
    barcode: "8 41234 10391 2",
    imageUrl: null,
  },
  {
    id: "itm-11022",
    sku: "SKU-11022",
    name: "Cold Brew Concentrate 1L",
    categoryId: "cat-bev",
    categoryName: "Beverages",
    locationId: "loc-s12",
    locationName: "Store 12",
    bin: "Back room, Shelf 2",
    onHand: 4,
    reorderPoint: 30,
    reorderQty: 60,
    status: "critical",
    supplierId: "sup-meridian",
    supplierName: "Meridian Foods Co.",
    unitCost: 9.75,
    sellPrice: 18.0,
    barcode: "8 41234 11022 7",
    imageUrl: null,
  },
  {
    id: "itm-10777",
    sku: "SKU-10777",
    name: "Kraft Shipping Boxes M",
    categoryId: "cat-pkg",
    categoryName: "Packaging",
    locationId: "loc-b",
    locationName: "Warehouse B",
    bin: "Aisle 7, Bin 01",
    onHand: 0,
    reorderPoint: 150,
    reorderQty: 300,
    status: "out_of_stock",
    supplierId: "sup-brightpack",
    supplierName: "BrightPack Supplies",
    unitCost: 0.82,
    sellPrice: 1.6,
    barcode: "8 41234 10777 9",
    imageUrl: null,
  },
  {
    id: "itm-10905",
    sku: "SKU-10905",
    name: "Citrus Dish Soap 5L",
    categoryId: "cat-cln",
    categoryName: "Cleaning",
    locationId: "loc-a",
    locationName: "Warehouse A",
    bin: "Aisle 5, Bin 09",
    onHand: 22,
    reorderPoint: 40,
    reorderQty: 60,
    status: "low",
    supplierId: "sup-brightpack",
    supplierName: "BrightPack Supplies",
    unitCost: 12.1,
    sellPrice: 21.5,
    barcode: "8 41234 10905 6",
    imageUrl: null,
  },
  {
    id: "itm-10488",
    sku: "SKU-10488",
    name: "Multigrain Crackers 200g",
    categoryId: "cat-snk",
    categoryName: "Snacks",
    locationId: "loc-s12",
    locationName: "Store 12",
    bin: "Aisle 2, Bin 18",
    onHand: 183,
    reorderPoint: 80,
    reorderQty: 300,
    status: "in_stock",
    supplierId: "sup-meridian",
    supplierName: "Meridian Foods Co.",
    unitCost: 1.95,
    sellPrice: 3.99,
    barcode: "8 41234 10488 4",
    imageUrl: null,
  },
  {
    id: "itm-11150",
    sku: "SKU-11150",
    name: "Vanilla Syrup 750ml",
    categoryId: "cat-bev",
    categoryName: "Beverages",
    locationId: "loc-a",
    locationName: "Warehouse A",
    bin: "Aisle 1, Bin 22",
    onHand: 2,
    reorderPoint: 24,
    reorderQty: 48,
    status: "critical",
    supplierId: "sup-north",
    supplierName: "Northstar Distributors",
    unitCost: 7.4,
    sellPrice: 14.0,
    barcode: "8 41234 11150 7",
    imageUrl: null,
  },
];

export const movements: Record<string, StockMovement[]> = {
  "itm-10234": [
    {
      id: "mv-1",
      itemId: "itm-10234",
      date: "2026-08-05",
      type: "sold",
      change: -18,
      balance: 64,
      userName: "POS",
      note: null,
    },
    {
      id: "mv-2",
      itemId: "itm-10234",
      date: "2026-08-02",
      type: "received",
      change: 150,
      balance: 82,
      userName: "M. Reyes",
      note: null,
    },
    {
      id: "mv-3",
      itemId: "itm-10234",
      date: "2026-07-28",
      type: "adjusted",
      change: -4,
      balance: 68,
      userName: "A. Chen",
      note: "damaged",
    },
  ],
};

export const purchaseOrders: PurchaseOrder[] = [
  {
    id: "po-2041",
    number: "PO-2041",
    supplierId: "sup-north",
    supplierName: "Northstar Distributors",
    status: "sent",
    orderDate: "2026-08-01",
    expectedDate: "2026-08-08",
    itemCount: 3,
    total: 6140,
    lines: [
      {
        id: "pol-1",
        itemId: "itm-10234",
        sku: "SKU-10234",
        itemName: "Organic Rolled Oats 25kg",
        expectedQty: 150,
        receivedQty: 0,
        unitCost: 18.4,
      },
      {
        id: "pol-2",
        itemId: "itm-10488",
        sku: "SKU-10488",
        itemName: "Multigrain Crackers 200g",
        expectedQty: 300,
        receivedQty: 0,
        unitCost: 1.95,
      },
      {
        id: "pol-3",
        itemId: "itm-10391",
        sku: "SKU-10391",
        itemName: "Sparkling Water 12pk",
        expectedQty: 240,
        receivedQty: 0,
        unitCost: 6.2,
      },
    ],
  },
  {
    id: "po-2040",
    number: "PO-2040",
    supplierId: "sup-meridian",
    supplierName: "Meridian Foods Co.",
    status: "partially_received",
    orderDate: "2026-07-28",
    expectedDate: "2026-08-04",
    itemCount: 6,
    total: 12860.5,
    lines: [],
  },
  {
    id: "po-2039",
    number: "PO-2039",
    supplierId: "sup-brightpack",
    supplierName: "BrightPack Supplies",
    status: "draft",
    orderDate: null,
    expectedDate: null,
    itemCount: 2,
    total: 2410,
    lines: [],
  },
  {
    id: "po-2038",
    number: "PO-2038",
    supplierId: "sup-meridian",
    supplierName: "Meridian Foods Co.",
    status: "received",
    orderDate: "2026-07-20",
    expectedDate: "2026-07-26",
    itemCount: 8,
    total: 9320.75,
    lines: [],
  },
  {
    id: "po-2037",
    number: "PO-2037",
    supplierId: "sup-north",
    supplierName: "Northstar Distributors",
    status: "received",
    orderDate: "2026-07-14",
    expectedDate: "2026-07-19",
    itemCount: 4,
    total: 5075.2,
    lines: [],
  },
];

export const reorderAlerts: ReorderAlert[] = [
  {
    id: "ra-1",
    itemId: "itm-11022",
    sku: "SKU-11022",
    itemName: "Cold Brew Concentrate",
    locationName: "Store 12",
    supplierId: "sup-meridian",
    supplierName: "Meridian Foods Co.",
    onHand: 4,
    minimum: 30,
    suggestedQty: 60,
    severity: "critical",
  },
  {
    id: "ra-2",
    itemId: "itm-10777",
    sku: "SKU-10777",
    itemName: "Kraft Shipping Boxes M",
    locationName: "Warehouse B",
    supplierId: "sup-brightpack",
    supplierName: "BrightPack Supplies",
    onHand: 0,
    minimum: 150,
    suggestedQty: 300,
    severity: "critical",
  },
  {
    id: "ra-3",
    itemId: "itm-11150",
    sku: "SKU-11150",
    itemName: "Vanilla Syrup 750ml",
    locationName: "Warehouse A",
    supplierId: "sup-north",
    supplierName: "Northstar Distributors",
    onHand: 2,
    minimum: 24,
    suggestedQty: 48,
    severity: "critical",
  },
  {
    id: "ra-4",
    itemId: "itm-10234",
    sku: "SKU-10234",
    itemName: "Organic Rolled Oats 25kg",
    locationName: "Warehouse A",
    supplierId: "sup-north",
    supplierName: "Northstar Distributors",
    onHand: 64,
    minimum: 75,
    suggestedQty: 150,
    severity: "low",
  },
  {
    id: "ra-5",
    itemId: "itm-10905",
    sku: "SKU-10905",
    itemName: "Citrus Dish Soap 5L",
    locationName: "Warehouse A",
    supplierId: "sup-brightpack",
    supplierName: "BrightPack Supplies",
    onHand: 22,
    minimum: 40,
    suggestedQty: 60,
    severity: "low",
  },
];

const trend = [438, 441, 437, 452, 448, 461, 456, 470, 482.9].map((v, i) => ({
  date: `2026-07-${String(9 + i * 3).padStart(2, "0")}`,
  value: v * 1000,
}));

export const dashboard: DashboardSummary = {
  totalSkus: 1284,
  totalSkusChangePct: 3.2,
  lowStockItems: 18,
  lowStockLocations: 3,
  openPurchaseOrders: 7,
  awaitingReceipt: 2,
  inventoryValue: 482900,
  inventoryValueChangePct: 1.8,
  stockTrend: trend,
  topAlerts: reorderAlerts.slice(0, 4),
  recentActivity: [
    {
      id: "act-1",
      type: "received",
      itemName: "Sparkling Water 12pk",
      change: 240,
      locationName: "Warehouse A",
      userName: "M. Reyes",
      at: "2026-08-07T09:12:00Z",
    },
    {
      id: "act-2",
      type: "sold",
      itemName: "Organic Rolled Oats 25kg",
      change: -18,
      locationName: "Store 12",
      userName: "POS",
      at: "2026-08-07T08:47:00Z",
    },
    {
      id: "act-3",
      type: "adjusted",
      itemName: "Kraft Shipping Boxes M",
      change: -6,
      locationName: "Warehouse B",
      userName: "A. Chen",
      at: "2026-08-06T16:20:00Z",
    },
  ],
};

export const reports: ReportsSummary = {
  inventoryValueTrend: trend,
  valueFrom: 438000,
  valueTo: 482900,
  turnoverByCategory: [
    { categoryId: "cat-bev", label: "Bev", turnover: 0.82 },
    { categoryId: "cat-dry", label: "Dry", turnover: 0.55 },
    { categoryId: "cat-snk", label: "Snk", turnover: 0.68 },
    { categoryId: "cat-cln", label: "Cln", turnover: 0.34 },
    { categoryId: "cat-pkg", label: "Pkg", turnover: 0.46 },
  ],
  topMovers: [
    { itemId: "itm-10391", itemName: "Sparkling Water 12pk", changePct: 22 },
    { itemId: "itm-10234", itemName: "Organic Rolled Oats 25kg", changePct: 14 },
    { itemId: "itm-10777", itemName: "Kraft Shipping Boxes M", changePct: -9 },
  ],
};

// Deterministic 12 × 4 bin grid — no Math.random, so SSR and client agree.
const MAP_COLUMNS = 12;
const MAP_ROWS = 4;
// Length 7 — coprime with the 12 columns, so rows don't repeat into stripes.
const FILL_CYCLE = [1, 0.7, 0.3, 0, 0.55, 0.3, 0.7];

/** Aisle 3, Bin 12 — the bin the oats item and the mockup both point at. */
const HIGHLIGHTED = (3 - 1) * MAP_COLUMNS + (12 - 1);

export const warehouseMaps: Record<string, WarehouseMap> = Object.fromEntries(
  locations.map((loc, locIndex) => [
    loc.id,
    {
      locationId: loc.id,
      columns: MAP_COLUMNS,
      cells: Array.from({ length: MAP_COLUMNS * MAP_ROWS }, (_, i) => {
        const aisle = Math.floor(i / MAP_COLUMNS) + 1;
        const bin = (i % MAP_COLUMNS) + 1;
        const fill = FILL_CYCLE[(i + locIndex * 5) % FILL_CYCLE.length];
        const highlighted = loc.id === "loc-a" && i === HIGHLIGHTED;
        return {
          id: `${loc.id}-a${aisle}-b${bin}`,
          label: `Aisle ${aisle}, Bin ${String(bin).padStart(2, "0")}`,
          fill,
          itemName: highlighted ? "Organic Rolled Oats 25kg" : null,
          units: highlighted ? 64 : Math.round(fill * 120),
          lastCountedAt: highlighted ? "2026-08-05" : null,
        };
      }),
    } satisfies WarehouseMap,
  ]),
);

export const team: TeamMember[] = [
  {
    id: "usr-1",
    name: "Jordan Diaz",
    email: "jordan@stocklane.co",
    role: "admin",
    locationLabel: "All locations",
    status: "active",
  },
  {
    id: "usr-2",
    name: "Mia Reyes",
    email: "mia@stocklane.co",
    role: "manager",
    locationLabel: "Warehouse A",
    status: "active",
  },
  {
    id: "usr-3",
    name: "Andre Chen",
    email: "andre@stocklane.co",
    role: "staff",
    locationLabel: "Warehouse B",
    status: "active",
  },
  {
    id: "usr-4",
    name: "Priya Nair",
    email: "priya@stocklane.co",
    role: "staff",
    locationLabel: "Store 12",
    status: "invited",
  },
];
